### ISSUE TITLE
stupid question

### ISSUE THREAD

**Issue by 0067sdsm** [spyboy-productions/r4ven#3]
Pls help lol
what is Discord Webhoook url

**Comment by 0067sdsm** [comment]
oh nevermind i got it lol but when i open it on my VM this happens:

INFO:     Started server process [1728]                                                         
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:52106 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:52106 - "GET /dwebhook.js HTTP/1.1" 404 Not Found                                                                                                  
INFO:     127.0.0.1:52106 - "POST /location_update HTTP/1.1" 500 Internal Server Error                                                                                 
ERROR:    Exception in ASGI application                                                                                                                                
Traceback (most recent call last):                                                                                                                                     
  File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi                                                                      
    result = await app(self.scope, self.receive, self.send)                                                                                                            
  File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__                                                                      
    return await self.app(scope, receive, send)                                                                                                                        
  File "/usr/lib/python3/dist-packages/fastapi/applications.py", line 270, in __call__                                                                                 
    await super().__call__(scope, receive, send)                                                                                                                       
  File "/usr/lib/python3/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3/dist-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/lib/python3/dist-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/lib/python3/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/lib/python3/dist-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/usr/lib/python3/dist-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sdsm0067/stuff/tools/r4ven/webapp_backend.py", line 37, in update_location
    update_webhook(discord_webhook, data)
  File "/home/sdsm0067/stuff/tools/r4ven/utils.py", line 25, in update_webhook
    requests.request("POST", webhook, headers=headers, data=request_payload)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
INFO:     127.0.0.1:52120 - "POST /location_update HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/lib/python3/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3/dist-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/lib/python3/dist-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/lib/python3/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/lib/python3/dist-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/usr/lib/python3/dist-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sdsm0067/stuff/tools/r4ven/webapp_backend.py", line 37, in update_location
    update_webhook(discord_webhook, data)
  File "/home/sdsm0067/stuff/tools/r4ven/utils.py", line 25, in update_webhook
    requests.request("POST", webhook, headers=headers, data=request_payload)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
INFO:     127.0.0.1:52134 - "POST /location_update HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/lib/python3/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3/dist-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/lib/python3/dist-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/lib/python3/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/lib/python3/dist-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/usr/lib/python3/dist-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sdsm0067/stuff/tools/r4ven/webapp_backend.py", line 37, in update_location
    update_webhook(discord_webhook, data)
  File "/home/sdsm0067/stuff/tools/r4ven/utils.py", line 25, in update_webhook
    requests.request("POST", webhook, headers=headers, data=request_payload)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
INFO:     127.0.0.1:48458 - "POST /location_update HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application                                                                                                                                
Traceback (most recent call last):                                                                                                                                     
  File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi                                                                      
    result = await app(self.scope, self.receive, self.send)                                                                                                            
  File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__                                                                      
    return await self.app(scope, receive, send)                                                                                                                        
  File "/usr/lib/python3/dist-packages/fastapi/applications.py", line 270, in __call__                                                                                 
    await super().__call__(scope, receive, send)                                                                                                                       
  File "/usr/lib/python3/dist-packages/starlette/applications.py", line 124, in __call__                                                                               
    await self.middleware_stack(scope, receive, send)                                                                                                                  
  File "/usr/lib/python3/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3/dist-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/lib/python3/dist-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/lib/python3/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3/dist-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/lib/python3/dist-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/usr/lib/python3/dist-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sdsm0067/stuff/tools/r4ven/webapp_backend.py", line 37, in update_location
    update_webhook(discord_webhook, data)
  File "/home/sdsm0067/stuff/tools/r4ven/utils.py", line 25, in update_webhook
    requests.request("POST", webhook, headers=headers, data=request_payload)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/sdsm0067/.local/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?

**Comment by thisisshubhamkumar** [comment]
> Pls help lol what is Discord Webhoook url

Discord's built in Webhooks function as an easy way to get automated messages and data updates sent to a text channel in your server.

(set up a channel in your discord server with webhook integration)

https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks

if not have a discord account and sever make one, it's free.

https://discord.com/
